inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.3
  TargetRailsVersion: 6.1.3.1
  NewCops: enable #rubcopの新しいバージョンの機能を自動追加
  Exclude: #除外ファイル
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - "db/schema.rb"
    - 'node_modules/**/*'
    # 日本語でのコメントを許可
  Style/AsciiComments:
    Enabled: false
  Rails: #ファイルパスからどこをチェックすればいいか自動で判断
    Enabled: true
    # モジュール名::クラス名の定義を許可
  ClassAndModuleChildren:
    Enabled: false
    # クラスのコメント必須を無視
  Documentation:
    Enabled: false